// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi2LIJ0SKxLrS6LRADnw9fJbdv7UYGIs0',
    appId: '1:603583123085:web:2c389f2174c56e0ef55cc4',
    messagingSenderId: '603583123085',
    projectId: 'suaxe-web-73744',
    authDomain: 'suaxe-web-73744.firebaseapp.com',
    storageBucket: 'suaxe-web-73744.firebasestorage.app',
    measurementId: 'G-5LYGTTJE4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIldcYWbhFo4qYe2f8zMIF4zAitIgVVdQ',
    appId: '1:603583123085:android:19b182b24b926e41f55cc4',
    messagingSenderId: '603583123085',
    projectId: 'suaxe-web-73744',
    storageBucket: 'suaxe-web-73744.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzpIeyerxe-IzZ_bRC-_4Ds9zQUL0_kxU',
    appId: '1:603583123085:ios:9d6f36d028f1255cf55cc4',
    messagingSenderId: '603583123085',
    projectId: 'suaxe-web-73744',
    storageBucket: 'suaxe-web-73744.firebasestorage.app',
    androidClientId: '603583123085-bmjamkn87vmeo5h9ks3om98pddl1mgaj.apps.googleusercontent.com',
    iosClientId: '603583123085-igs4jr8o6ahvuk8vms0g3h6mq1vglj50.apps.googleusercontent.com',
    iosBundleId: 'com.example.suaxeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzpIeyerxe-IzZ_bRC-_4Ds9zQUL0_kxU',
    appId: '1:603583123085:ios:9d6f36d028f1255cf55cc4',
    messagingSenderId: '603583123085',
    projectId: 'suaxe-web-73744',
    storageBucket: 'suaxe-web-73744.firebasestorage.app',
    androidClientId: '603583123085-bmjamkn87vmeo5h9ks3om98pddl1mgaj.apps.googleusercontent.com',
    iosClientId: '603583123085-igs4jr8o6ahvuk8vms0g3h6mq1vglj50.apps.googleusercontent.com',
    iosBundleId: 'com.example.suaxeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi2LIJ0SKxLrS6LRADnw9fJbdv7UYGIs0',
    appId: '1:603583123085:web:169ea473e0c28839f55cc4',
    messagingSenderId: '603583123085',
    projectId: 'suaxe-web-73744',
    authDomain: 'suaxe-web-73744.firebaseapp.com',
    storageBucket: 'suaxe-web-73744.firebasestorage.app',
    measurementId: 'G-9Z9N47557N',
  );
}
